services:
  react-app:
    build:
      context: . # Build the Dockerfile in the current directory
      dockerfile: Dockerfile
    ports:
      - "3002:3000" # Map port 3000 on the host to port 80 in the container
    volumes:
      - .:/app # Mount the local project folder to the container for live updates
      - /app/node_modules # Ensure node_modules doesn't get overwritten
    stdin_open: true
    tty: true